project:
  type: book
  output-dir: ../../docs/statistics-probability

book:
  title: "Statistiques & Probabilit√©s"
  author: "Guillaume Gilles"
  date: "1/27/2026"
  search: 
    location: sidebar
  navbar:
    right:
      - href: ../about/README.html
      - href: ../blog.html 
  chapters:
    - index.qmd
    - part: "Statistiques desciptives" 
      chapters:
        - descriptives.qmd
    # References
    - references.qmd

lang: fr

bibliography: references.bib

format:
  html:
    theme:
      light: light.scss
